language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE=PurBeurreSite.settings.travis

services:
  - postgresql

script:
  - python3 ./manage.py collectstatic
  - python3 ./manage.py makemigrations
  - python3 ./manage.py migrate
