language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env:
  global:
    - MOZ_HEADLESS=1
    - DJANGO_SETTINGS_MODULE=PurBeurreSite.settings.travis

addons:
  firefox: latest

services:
  - postgresql
  -
script:
  - python3 ./manage.py collectstatic
  - python3 ./manage.py makemigrations
  - python3 ./manage.py migrate
  - python3 ./manage.py fill_db
  - python3 ./manage.py test

