language: python
python:
  - '3.7'

dist: xenial

before_script:
  - pip install -r requirements.txt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

env: DJANGO_SETTINGS_MODULE=PurBeurreSite.settings.travis

services:
  - postgresql
  - xvfb

script:
  - python3 ./manage.py collectstatic
#  - python3 ./manage.py makemigrations
  - python3 ./manage.py migrate
  - python3 ./manage.py fill_db
  - xvfb-run make test
#  - python3 ./manage.py test
