# Generated by Django 3.1.5 on 2021-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('nutri_score', models.CharField(max_length=2, null=True)),
                ('ingredient', models.TextField()),
                ('url', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
