# Generated by Django 3.1.5 on 2021-01-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url_off',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.TextField(null=True),
        ),
    ]
